# Site settings
title: Porcelain Throne Waterfalls
header-img: img/coffee.jpg
email: nick.androul@gmail.com
copyright_name: prppCorp
description: "Meaningless, yet it exists. Just like you :)."
baseurl: "/PorcelainThroneWaterfalls"
url:
twitter_username:
github_username: nickAndroulakis
facebook_username: nick.androulakis.5
email_username: nick.androul@gmail.com
spotify_username: mightycarl

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-108639413-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins: [jekyll-paginate, jekyll-feed]
